# -*- coding: utf-8 -*-
"""matrix_multi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tDimptNtUg6kQm--t3H4LQSy8nrjm2mb
"""

def matrix_multiplication(matrix1, matrix2):
    """
    Performs matrix multiplication between two matrices.

    Args:
    matrix1 (list of lists): The first matrix.
    matrix2 (list of lists): The second matrix.

    Returns:
    list of lists: The result of matrix multiplication.
    """
    # Get the dimensions of the matrices
    rows1, cols1 = len(matrix1), len(matrix1[0])
    rows2, cols2 = len(matrix2), len(matrix2[0])

    # Check if multiplication is possible
    if cols1 != rows2:
        raise ValueError("Matrix dimensions are not compatible for multiplication.")

    # Initialize result matrix with zeros
    result = [[0 for _ in range(cols2)] for _ in range(rows1)]

    # Perform matrix multiplication
    for i in range(rows1):
        for j in range(cols2):
            for k in range(cols1):
                result[i][j] += matrix1[i][k] * matrix2[k][j]

    return result

# Example matrices
matrix1 = [[1, 2, 3],
           [4, 5, 6]]

matrix2 = [[7, 8],
           [9, 10],
           [11, 12]]

result = matrix_multiplication(matrix1, matrix2)
print("Result of matrix multiplication:")
for row in result:
    print(row)